# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C86xzfsfCJBXyetVo7N4nQkoQ40pGont
"""

import time
minusculas = ""
for i in range(ord('a'), ord('z') + 1):
    minusculas += chr(i)
mayusculas = ""
for i in range(ord('A'), ord('Z') + 1):
    mayusculas += chr(i)
numeros = "0123456789"
alphabet = minusculas + mayusculas + numeros
contraseña = "uide"
intentos = 0
inicio = time.time()
longitud = 1
encontrado = False
while not encontrado:
    indices = [0] * longitud
    while True:
        intento = ""
        for i in indices:
            intento += alphabet[i]
        intentos += 1
        if intento == contraseña:
            encontrado = True
            break
        pos = longitud - 1
        while pos >= 0:
            indices[pos] += 1
            if indices[pos] < len(alphabet):
                break
            else:
                indices[pos] = 0
                pos -= 1
        if pos < 0:
            break
    longitud += 1
fin = time.time()
if encontrado:
    print("Contraseña encontrada:", intento)
    print("Intentos:", intentos)
    print("Tiempo:", fin - inicio, "segundos")
else:
    print("No se encontró la contraseña")